INSERT INTO students(first_name, last_name, email) VALUES ('Mike', 'Smith', 'abc@pnc.com')
INSERT INTO students(first_name, last_name, email) VALUES ('Tom', 'Hanks', 'bcd@pnc.com')
INSERT INTO students(first_name, last_name, email) VALUES ('Brad', 'Pitt', 'def@pnc.com')
INSERT INTO students(first_name, last_name, email) VALUES ('Shawn', 'Penn', 'fgh@pnc.com')
INSERT INTO students(first_name, last_name, email) VALUES ('John', 'Doe', 'thy@pnc.com')